name = "dpp-sync-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "dpp-sync"
database_id = "3c0aaf5e-c0cf-43d9-a725-e869ad62162d"
migrations_dir = "migrations"

[durable_objects]
bindings = [
  { name = "SYNC_PUSH_COORDINATOR", class_name = "SyncPushCoordinator" },
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncPushCoordinator"]

[[routes]]
pattern = "dpp-sync.586726.xyz"
zone_name = "586726.xyz"
custom_domain = true

[env.test]
name = "dpp-sync-test"
workers_dev = true

[[env.test.d1_databases]]
binding = "DB"
database_name = "dpp-sync-test"
database_id = "5bbc552b-24eb-459a-b8ce-460582a24273"
migrations_dir = "migrations"

[env.test.durable_objects]
bindings = [
  { name = "SYNC_PUSH_COORDINATOR", class_name = "SyncPushCoordinator" },
]

[[env.test.migrations]]
tag = "v1"
new_sqlite_classes = ["SyncPushCoordinator"]

[[env.test.routes]]
pattern = "dpp-sync-test.586726.xyz"
zone_name = "586726.xyz"
custom_domain = true
